/* libjssql - a JDBC-like SQL API for SpiderMonkey JS
 * Copyright (C) 2013 Mindbit SRL
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of version 2.1 of the GNU Lesser General Public
 * License as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#ifndef jspgsql_h___
#define jspgsql_h___

#define POSTGRES_URI				"postgresql://"
#define POSTGRES_URI_LEN			13
#define POSTGRES_DEFAULT_PORT			5432
#define POSTGRES_CONNECTOR_LEN			256

#define TEXT_RESULT				0
#define BINARY_RESULT				1

#define SIMPLE_STATEMENT			0
#define PREPARED_STATEMENT			1

#define MAX_PARAMETERS				99

#define POSTGRES_AUTOGENERATED_STRING		" RETURNING *"
#define POSTGRES_AUTOGENERATED_STRING_LENGTH	12
#define NO_GENERATED_KEYS			0
#define RETURN_GENERATED_KEYS			1

#if 0

#include <jsapi.h>

JSBool JS_PgsqlConstructAndRegister(JSContext *cx, JSObject *global);

#endif

#endif
