/* SPDX-License-Identifier: MIT */

#ifndef jspgsql_h___
#define jspgsql_h___

#define POSTGRES_URI				"postgresql://"
#define POSTGRES_URI_LEN			13
#define POSTGRES_DEFAULT_PORT			5432
#define POSTGRES_CONNECTOR_LEN			256

#define TEXT_RESULT				0
#define BINARY_RESULT				1

#define SIMPLE_STATEMENT			0
#define PREPARED_STATEMENT			1

#define MAX_PARAMETERS				99

#define POSTGRES_AUTOGENERATED_STRING		" RETURNING *"
#define POSTGRES_AUTOGENERATED_STRING_LENGTH	12
#define NO_GENERATED_KEYS			0
#define RETURN_GENERATED_KEYS			1

duk_bool_t js_pgsql_construct_and_register(duk_context *ctx);

#endif
